export const FETCH_POKEMONS = "FETCH_POKEMONS";
export const FETCH_POKEMONS_SUCCEEDED = "FETCH_POKEMONS_SUCCEEDED";
export const FETCH_POKEMONS_FAILED = "FETCH_POKEMONS_FAILED";

export const FETCH_POKEMON = "FETCH_POKEMON";
export const FETCH_POKEMON_SUCCEEDED = "FETCH_POKEMON_SUCCEEDED";
export const FETCH_POKEMON_FAILED = "FETCH_POKEMON_FAILED";

export const FIND_POKEMON_BY_NAME = "FIND_POKEMON_BY_NAME";
export const FIND_POKEMON_BY_TYPES = "FIND_POKEMON_BY_TYPES";

export const FETCH_PAGE = "FETCH_PAGE";